#!/usr/bin/env bash
# mova - Multi-homed Nova command-line client wrapper

if [[ -z $MOVA_PATH ]]; then
    MOVA_PATH=~/.mova
fi

MOVA_ENVIRONMENT_PATH=$MOVA_PATH/environments
MOVA_CURRENT_PATH=$MOVA_PATH/current


# Read current environment
current=
if [[ -e $MOVA_CURRENT_PATH ]]; then
    current=$(cat $MOVA_CURRENT_PATH)
fi

# Ensure directory containing `novarc` files exists
if [[ ! -e $MOVA_ENVIRONMENT_PATH ]]; then
    echo Mova environment path $MOVA_ENVIRONMENT_PATH doesn\'t exist, please create it...
    exit 1
fi

# List environments
if [[ -z $1 ]]; then
    for e in `ls $MOVA_ENVIRONMENT_PATH`; do
        if [[ $e = $current ]]; then
            echo "$e (current)"
        else
            echo "$e"
        fi
    done
    exit 0
fi

# Change current environment
if [[ $1 = use ]]; then
    if [[ -z $2 ]]; then
        echo "usage: mova use <env>"
        exit 1
    fi
    echo $2 > $MOVA_CURRENT_PATH
    exit 0
fi

# Ensure environment was specified
if [[ -z $current ]]; then
    echo No current environment specified, try 'mova use <env>'.
    exit 1
fi

# Run nova command under current environment
env $(cat $MOVA_ENVIRONMENT_PATH/$current| tr '\n' ' ') nova $*
